steps:
  - name: 'node:20'
    dir: 'frontend'
    entrypoint: 'npm'
    args: ['install']

  - name: 'node:20'
    dir: 'frontend'
    entrypoint: 'bash'
    args:
      - -c
      - |
        chmod +x node_modules/.bin/react-scripts
        npx react-scripts build

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    dir: 'frontend'
    entrypoint: 'bash'
    args:
      - -c
      - |
        gcloud config set app/cloud_build_timeout 1600
        gcloud app deploy --quiet

timeout: '1600s'

options:
  logging: CLOUD_LOGGING_ONLY
