GET http://localhost:5000/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJ0ZXMiLCJlbWFpbCI6InRlc0B0ZXMuY29tIiwiaWF0IjoxNzQ4MjMwNjQyLCJleHAiOjE3NDgyMzA2NjJ9.d04k8vOdw7jU4F9m3tkAuZBZKbUHexTbBNsoJb6XLp4

###

POST http://localhost:5000/user 
Content-Type: application/json

{
    "name": "tes",
    "email": "tes@tes.com",
    "password": "12345",
    "confPassword" : "12345"
}

### 

POST http://localhost:5000/login 
Content-Type: application/json

{
    "email": "tes@tes.com",
    "password": "12345"
}

### 

GET http://localhost:5000/token

### 

DELETE http://localhost:5000/logout


# PUT http://localhost:5000/edit-user/14
# Content-Type: application/json

# {
#     "name": "tessss",
#     "email": "tesss@tessss.com",
#     "gender": "Male"
# }

# ###

# DELETE http://localhost:5000/delete-user/17


# ###

# POST http://localhost:5000/login
# Content-Type: application/json

# {
   
#     "email": "tes@tes.com",
#     "password": "12345"
# }



# ###

# DELETE http://localhost:5000/logout